version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - haines

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - haines
